spring.application.name=feed-back-server
server.port=${PORT:8080}

# 1. DataSource - Direct connection (không pooler)
spring.datasource.url=jdbc:postgresql://ep-shiny-poetry-aorxjbej.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_6Qsio7JcBjIH

# 2. HikariCP - giảm pool size vì Neon direct connection giới hạn
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000

# 3. JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# 4. JWT
app.jwt.secret=Thang@@Cho_Naocotin@!@!hdoccai...Naythi_@@bubuoiloN200123
app.jwt.expiration-ms=86400000